export const migrations = [
  {
    MigrationID: 'MIG-1001',
    CustomerID: 'C-001',
    Customer: 'Acme Corp',
    Stage: 'Discovery',
    PreviousATS: 'Greenhouse',
    Status: 'OnTrack',
    Owner: 'owner1@example.com',
    GitHubLink: 'https://github.com/lucas-loxo/migration-hub-ui',
    Days: 3,
  },
  {
    MigrationID: 'MIG-1002',
    CustomerID: 'C-002',
    Customer: 'Globex',
    Stage: 'Data Export',
    PreviousATS: 'Lever',
    Status: 'Behind',
    Owner: 'owner1@example.com',
    GitHubLink: 'https://github.com/facebook/react',
    Days: 7,
  },
  {
    MigrationID: 'MIG-1003',
    CustomerID: 'C-003',
    Customer: 'Initech',
    Stage: 'Mapping',
    PreviousATS: 'Workday',
    Status: 'OnTrack',
    Owner: 'owner2@example.com',
    GitHubLink: 'https://github.com/vitejs/vite',
    Days: 12,
  },
  {
    MigrationID: 'MIG-1004',
    CustomerID: 'C-004',
    Customer: 'Umbrella Co',
    Stage: 'Import',
    PreviousATS: 'Greenhouse',
    Status: 'Behind',
    Owner: 'owner2@example.com',
    GitHubLink: 'https://github.com/tailwindlabs/tailwindcss',
    Days: 5,
  },
  {
    MigrationID: 'MIG-1005',
    CustomerID: 'C-005',
    Customer: 'Wayne Enterprises',
    Stage: 'Validation',
    PreviousATS: 'Custom',
    Status: 'OnTrack',
    Owner: 'owner3@example.com',
    GitHubLink: 'https://github.com/chartjs/Chart.js',
    Days: 2,
  },
  {
    MigrationID: 'MIG-1006',
    CustomerID: 'C-006',
    Customer: 'Stark Industries',
    Stage: 'Go-Live',
    PreviousATS: 'Workday',
    Status: 'OnTrack',
    Owner: 'owner1@example.com',
    GitHubLink: 'https://github.com/remix-run/react-router',
    Days: 1,
  },
]

export const stagePerformance = [
  { Stage: 'Discovery', Count: 1 },
  { Stage: 'Data Export', Count: 1 },
  { Stage: 'Mapping', Count: 1 },
  { Stage: 'Import', Count: 1 },
  { Stage: 'Validation', Count: 1 },
  { Stage: 'Go-Live', Count: 1 },
]


